# Generated by Django 6.1.1 on 2026-09-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='deleted',
        ),
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
